version: '3'

services: 
  web:
    image: ml6/people-counter-dashboard
    build: .
    container_name: pc-dashboard
    ports:
      - "80:3000"
    environment: 
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      
  rethinkdb:
    image: rethinkdb:2.4
    container_name: pc-rethinkdb
    ports:
      - "28015:28015"
      - "3333:8080"
    volumes: 
      - "rethinkdb-data:/data"

volumes:
  rethinkdb-data: